DROP TABLE IF EXISTS surveys;

CREATE TABLE surveys (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    name TEXT NOT NULL,
    age INTEGER NOT NULL,
    email TEXT NOT NULL,
    zipcode INTEGER NOT NULL
)